name: LikeC4 Export
description: Export LikeC4 views to png
author: likec4
inputs:
  src:
    description: directory with likec4 sources
    required: false
    default: '.'
  out:
    description: directory for generated png
    required: false
    default: '.'

runs:
  using: docker
  image: docker://ghcr.io/likec4/actions-export:v1.0.9
  args:
    - ${{ inputs.out }}
    - ${{ inputs.src }}

branding:
  icon: image
  color: gray-dark